services:
  - type: web
    name: ads-recommendation-system
    env: python
    plan: free

    pythonVersion: "3.10"

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn app:app --host=0.0.0.0 --port=$PORT
