services:
  - type: web
    name: ads-recommendation-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host=0.0.0.0 --port=$PORT"
    plan: free
    region: oregon
    pythonVersion: 3.10.13
